#!/usr/bin/python3
#Error program 
'''def handlexception(func):
    def wrapper():
        try:
            return func()
        except ZeroDivisionError:
            print("there was zero division error")
        except TypeError:
            print("there was type error")
        except Exception:
            print("there was an error")
    return wrapper

@handlexception
def causeError():
    return 1/0

causeError() ''' 


# PROGRAM NO 2 

